version: 0.2

phases:
  install:
    commands:
      - echo "Installing Serverless..."
      - npm install
  pre_build:
    commands:
      - echo "Preparing to deploy..."
  build:
    commands:
      - echo "Deployment started on `date`"
      - echo "Deploying with the Serverless Framework"
      - npx serverless deploy -s $ENV_NAME
  post_build:
    commands:
      - echo "Deployment completed on `date`"
cache:
  paths:
    - node_modules/**