version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing pnpm..."
      - npm install -g pnpm
      - echo "Installing Serverless..."
      - pnpm install
  pre_build:
    commands:
      - echo "Preparing to deploy..."
  build:
    commands:
      - echo "Deployment started on `date`"
      - echo "Deploying with the Serverless Framework"
      - pnpm exec serverless deploy -s $ENV_NAME
  post_build:
    commands:
      - echo "Deployment completed on `date`"
cache:
  paths:
    - node_modules/**